name: Cypress E2E Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install modules
        run: npm ci
        working-directory: frontend

      - name: Build application
        run: npm run build
        working-directory: frontend

      - name: Start the server in the background
        run: npm run dev &
        working-directory: frontend

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          wait-on: http://localhost:4321
          working-directory: frontend
